
import { GoogleGenAI, Type, GenerateContentResponse } from "@google/genai";
import type { ConservationFact, GroundingChunk } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const askOceanQuestion = async (prompt: string): Promise<{ text: string, sources: GroundingChunk[] }> => {
  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `You are a marine biologist and oceanographer named Oceanica. Answer the following question about the ocean in an engaging and informative way. Question: "${prompt}"`,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });
    
    const text = response.text;
    const groundingMetadata = response.candidates?.[0]?.groundingMetadata;
    const sources = groundingMetadata?.groundingChunks || [];

    return { text, sources };

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to get a response from the depths of the AI ocean.");
  }
};

export const getOceanFacts = async (): Promise<ConservationFact[]> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: "Provide 6 important facts about ocean conservation and preservation. For each fact, provide a topic and a detailed explanation.",
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              topic: {
                type: Type.STRING,
                description: "The topic of the ocean conservation fact (e.g., Plastic Pollution).",
              },
              fact: {
                type: Type.STRING,
                description: "An important fact about the conservation topic.",
              },
            },
            required: ["topic", "fact"],
          },
        },
      },
    });

    const jsonText = response.text.trim();
    const facts = JSON.parse(jsonText);
    return facts as ConservationFact[];
    
  } catch (error) {
    console.error("Error fetching ocean facts from Gemini API:", error);
    // Provide fallback facts if the API fails
    return [
      { topic: "Plastic Pollution", fact: "Over 8 million tons of plastic enter the oceans each year, harming marine life and ecosystems. It's estimated that by 2050, there could be more plastic than fish in the ocean by weight." },
      { topic: "Overfishing", fact: "More than a third of the world's fish stocks are being fished at biologically unsustainable levels, threatening marine biodiversity and the livelihoods of millions of people." },
      { topic: "Coral Bleaching", fact: "Rising ocean temperatures due to climate change are causing widespread coral bleaching, where corals expel the algae living in their tissues, turning them white and vulnerable to disease and death." },
      { topic: "Ocean Acidification", fact: "The ocean absorbs about 30% of the CO2 released into the atmosphere, leading to increased acidity. This harms organisms like corals and shellfish by hindering their ability to build shells and skeletons." },
      { topic: "Marine Protected Areas (MPAs)", fact: "MPAs are crucial for conservation. They are designated areas where human activities are restricted to protect nature. Currently, only about 8% of the world's ocean is protected." },
      { topic: "Sustainable Seafood", fact: "Consumers can help protect the ocean by choosing sustainably sourced seafood. Look for certifications from groups like the Marine Stewardship Council (MSC) to make an informed choice." }
    ];
  }
};

export const generateOceanImage = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
            aspectRatio: '16:9',
        }
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error calling Gemini Image API:", error);
    throw new Error("Failed to generate an image from the AI ocean's depths.");
  }
};
